# Generated by Django 3.2.9 on 2021-11-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idUsuario',
            new_name='id',
        ),
    ]
