# Generated by Django 3.2.9 on 2021-11-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usuario_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='idUsuario',
        ),
    ]
